export const airports = [
  { code: "WAW", city: "Warszawa", name: "Lotnisko Chopina" },
  { code: "WMI", city: "Warszawa", name: "Modlin" },
  { code: "KRK", city: "Kraków", name: "Balice" },
  { code: "GDN", city: "Gdańsk", name: "Rębiechowo" },
  { code: "KTW", city: "Katowice", name: "Pyrzowice" },
  { code: "WRO", city: "Wrocław", name: "Strachowice" },
  { code: "POZ", city: "Poznań", name: "Ławica" },
  { code: "FCO", city: "Rzym", name: "Fiumicino" },
  { code: "CIA", city: "Rzym", name: "Ciampino" },
  { code: "BCN", city: "Barcelona", name: "El Prat" },
  { code: "GRO", city: "Girona", name: "Costa Brava" },
  { code: "LIS", city: "Lizbona", name: "Humberto Delgado" },
  { code: "PMI", city: "Palma", name: "Mallorca" },
  { code: "AGP", city: "Malaga", name: "Costa del Sol" },
  { code: "ANY", city: "Dowolne miejsce", name: "Najtańszy kierunek" },
] as const;